services:
  caddy:
    container_name: caddy-for-tailscale
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy_logs:/var/log/caddy
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - token-backend
    environment:
      - CADDY_DISABLE_HTTP_CHALLENGE=true
      - ACME_AGREE=true
      - ACME_EMAIL=admin@vpnsib.com
    healthcheck:
      test: ["CMD", "caddy", "validate", "--config", "/etc/caddy/Caddyfile"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  token-backend:
    driver: bridge
    name: token-backend

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
